name: Custom Action
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_URL: next-vercel-test-qa.vercel.app
  
on:
  workflow_dispatch
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: curl
      uses: enflo/curl-action@master
      with:
        args: |
          -X PATCH 'https://api.vercel.com/v9/projects/${{ secrets.VERCEL_PROJECT_ID }}/domains/${{ secrets.VERCEL_URL }}?teamId=${{ secrets.VERCEL_ORG_ID }}' \
          -H 'Authorization: Bearer ${{ secrets.VERCEL_QA_TOKEN }}' \
          -d '{"gitBranch": "QA", "redirect": "", "redirectStatusCode": ""}'
